<?php
// Plugin definition
$plugin = array(
  'title' => t('Bootopoly Brown'),
  'icon' => 'bootopoly_brown.png',
  'category' => t('Bootopoly'),
  'theme' => 'bootopoly_brown',
  'regions' => array(
    'slider' => t('Slider'),
    'slidergutter' => t('Slider Gutter'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
    'footercolumn1' => t('Footer First Column'),
    'footercolumn2' => t('Footer Second Column'),
    'footercolumn3' => t('Footer Third Column'),
  ),
);
