<?php
/**
 * @file
 * cod_schedule.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cod_schedule_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_event_timeslots'
  $field_bases['field_event_timeslots'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_event_timeslots',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(),
    'indexes' => array(
      'revision_id' => array(
        0 => 'revision_id',
      ),
    ),
    'locked' => 0,
    'module' => 'field_collection',
    'settings' => array(
      'hide_blank_items' => 1,
      'path' => '',
    ),
    'translatable' => 0,
    'type' => 'field_collection',
  );

  // Exported field_base: 'field_evttime_date'
  $field_bases['field_evttime_date'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_evttime_date',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'granularity' => array(
        'day' => 'day',
        'hour' => 'hour',
        'minute' => 'minute',
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'timezone_db' => 'UTC',
      'todate' => 'required',
      'tz_handling' => 'date',
    ),
    'translatable' => 0,
    'type' => 'datetime',
  );

  // Exported field_base: 'field_session_timeslot'
  $field_bases['field_session_timeslot'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_session_timeslot',
    'field_permissions' => array(
      'type' => 2,
    ),
    'foreign keys' => array(
      'field_collection_item' => array(
        'columns' => array(
          'target_id' => 'item_id',
        ),
        'table' => 'field_collection_item',
      ),
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'views',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 1,
          ),
        ),
        'view' => array(
          'args' => array(
            0 => 3200,
            1 => 'session',
          ),
          'display_name' => 'entityreference_1',
          'view_name' => 'cod_schedule_timeslot_widget',
        ),
      ),
      'target_type' => 'field_collection_item',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_timeslot_allowed_types'
  $field_bases['field_timeslot_allowed_types'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_timeslot_allowed_types',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'field_select_ct',
    'settings' => array(
      'allowed_values' => array(
        'bof_session' => 'BoF Session',
        'schedule_item' => 'Schedule Item',
        'session' => 'Session',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_cts',
  );

  // Exported field_base: 'field_timeslot_room'
  $field_bases['field_timeslot_room'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_timeslot_room',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(
      'cod_event_room' => array(
        'columns' => array(
          'target_id' => 'evtrid',
        ),
        'table' => 'cod_event_room',
      ),
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(),
      ),
      'target_type' => 'cod_event_room',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_timeslot_time'
  $field_bases['field_timeslot_time'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_timeslot_time',
    'field_permissions' => array(
      'type' => 0,
    ),
    'foreign keys' => array(
      'cod_event_time' => array(
        'columns' => array(
          'target_id' => 'evttid',
        ),
        'table' => 'cod_event_time',
      ),
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(),
      ),
      'target_type' => 'cod_event_time',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
